### ISSUE TITLE
1.8.9 Server Crash on StartUp (with chunkgen-1.8.9-1.3.0.jar)

### ISSUE THREAD

**Issue by 7934345** [gecgooden/chunkgen#17]
[17:36:24] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[17:36:24] [Thread-8/INFO] [VersionChecker]: Received version check from mod VersionChecker
[17:36:24] [Server thread/ERROR] [FML]:
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHI    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge.jar)
        UCHI    Forge{11.15.1.1855} [Minecraft Forge] (forge.jar)
        UCHI    abilstones{8.1.2.0} [Ability Stones] (Ability Stones 8.1.2.0.jar)
        UCHI    AutoSapling{1.0} [Auto Sapling] (AutoSapling 1.2 MC1.8.9.jar)
        UCHI    babymobs{1.4} [Baby Mobs] (BabyMobs-1.8.9-1.4.jar)
        UCHI    BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar)
        UCHI    betterbuilderswands{0.5.3} [Better Builder's Wands] (BetterBuildersWands-0.5.3-1.8.9r91+7e8699b.jar)
        UCHI    BetterThanBedrock{gibt-release} [Better Than Bedrock] (BetterThanBedrock-2.0.6_gibt-release.jar)
        UCHI    BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2001-universal.jar)
        UCHI    chameleoncreepers{1.3} [Chameleon Creepers] (ChameleonCreepers-1.8.9-1.3.jar)
        UCHI    ChestTransporter{2.2.1} [Chest Transporter] (ChestTransporter-2.2.1-MC1.8.9.jar)
        UCHI    chickens{1.3} [Chickens] (chickens-1.8.9-1.3.jar)
        UCHE    examplemod{1.0} [examplemod] (chunkgen-1.8.9-1.3.0.jar)
        UCHI    chunkgen{1.7.10-1.2.2} [ChunkGen] (chunkgen-1.8.9-1.3.0.jar)
        UCHI    compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar)
        UCHI    craftnstar{0.3.1} [Craftable Nether Star +] (craftnstar-1.8.9-0.3.1.jar)
        UCHI    dldungeonsjdg{1.8.10} [Doomlike Dungeons] (DoomlikeDungeons-1.8.10-MC1.8.9.jar)
        UCHI    endores{1.0-a.010} [End Ores] (End Ores-1.0-a.010.jar)
        UCHI    endercompass{1.2.2} [Ender Compass] (EnderCompass-1.8.9-1.2.2.jar)
        UCHI    endercrop{1.8.9-1.2} [Ender Crop] (endercrop-1.8.9-1.2.jar)
        UCHI    EnderZoo{1.8.9-1.1.3.35} [Ender Zoo] (EnderZoo-1.8.9-1.1.3.35.jar)
        UCHI    FFS{1.8.9-1.5.1.97} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.5.1.97.jar)
        UCHI    fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar)
        UCHI    ftfloocraft{1.8.9-0.2} [Floocraft] (Floocraft-1.8.9-0.2.jar)
        UCHI    graves{1.8.9-b47-universal} [Graves Mod] (graves-1.8.9-b47-universal.jar)
        UCHI    HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar)
        UCHI    hgp{Release} [Horizontal Glass Panes] (hgp-1.8.9-1.0.2.jar)
        UCHI    hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar)
        UCHI    InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.8.8.jar)
        UCHI    IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar)
        UCHI    journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar)
        UCHI    jaff{1.4.1_for_1.8.9} [Just a Few Fish] (JustAFewFish-1.4.1_for_1.8.9.jar)
        UCHI    lteleporters{1.0.0} [Lemon's Simple Teleporters] (LemonsSimpleTeleporters-1.0.1.jar)
        UCHI    magicclover{1.8-0.7.2} [Magic Clover] (magicclover-1.8-0.7.2.jar)
        UCHI    RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar)
        UCHI    MCA{1.8.9-5.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.2-universal.jar)
        UCHI    MelonBlockDrop{1.2.1} [Melon Block Drop] (MelonBlockDrop-1.2.1.jar)
        UCHI    MoreFurnaces{1.5.1} [More Furnaces] (MoreFurnaces-1.5.1-MC1.8.9.jar)
        UCHI    Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar)
        UCHI    netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar)
        UCHI    nmsot{1.1.2-mc1.8.9} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.2-mc1.8.9.jar)
        UCHI    PigManure{1.0.1} [Pig Manure] (pig-manure-1.0.1-mc1.8.9.jar)
        UCHI    placemod{2.1} [Placemod] (Placemod-2.1-1.8.9.jar)
        UCHI    pcb{1.5.0} [Portable Craft Bench] (portablecraftbench-1.8.9-1.5.0.jar)
        UCHI    progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar)
        UCHI    reborncore{1.4.1.15} [RebornCore] (RebornCore-1.8.9-1.4.1.15-universal.jar)
        UCHI    redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar)
        UCHI    rightclicktorch{1.8.9-1.0.2} [RightClickTorch] (rightclicktorch-1.8.9-1.0.2.jar)
        UCHI    Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar)
        UCHI    AS_Ruins{15.6} [Ruins Spawning System] (Ruins-1.8.8.jar)
        UCHI    sensorcraft{0.1.1} [SensorCraft] (sensorcraft-0.1.1-MC1.8.9.jar)
        UCHI    sheeeps{0.3.3} [Sheeeps!] (Sheeeps!-0.3.3.jar)
        UCHI    spawnercraft{1.8.9-2.3} [SpawnerCraft] (SpawnerCraft2-1.8.9-2.3.jar)
        UCHI    mod_lizzyanvil{1.0} [The Lizzy Anvil] (TheLizzyAnvil-1.8-1.0.jar)
        UCHI    throwabletorchmod{1.3} [ThrowableTorchMod] (throwabletorchmod-1.8.9-1.3.jar)
        UCHI    Trashcans{1.0.1} [Trashcans] (Trashcans-1.8.9-1.0.1.jar)
        UCHI    trashslot{2.0.7} [TrashSlot] (trashslot-mc1.8.9-2.0.7.jar)
        UCHI    AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.8.jar)
        UCHI    VeinMiner{0.31.4_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.4.unknown.jar)
        UCHI    VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.4.unknown.jar)
        UCHI    VersionChecker{1.2.5} [Version Checker] (VersionChecker-1.2.5.jar)
        UCHI    mod_lizzyxpbottle{1.0} [Worthwhile XP Bottles] (WorthwhileXPBottles-1.8-1.0.jar)
[17:36:24] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[17:36:24] [Server thread/ERROR] [FML]: Caught exception from examplemod
java.lang.NoSuchFieldError: dirt
        at com.example.examplemod.ExampleMod.init(ExampleMod.java:18) ~[ExampleMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge.jar:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[forge.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[forge.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205) [ko.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[17:36:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: dirt

        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NoSuchFieldError: dirt
        at com.example.examplemod.ExampleMod.init(ExampleMod.java:18) ~[ExampleMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge.jar:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:?]
        ... 5 more
[17:36:24] [Server thread/ERROR]: This crash report has been saved to: G:\minecraft-forge\server189\.\crash-reports\crash-2016-04-10_17.36.24-server.txt
[17:36:24] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[17:36:24] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:36:24] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by gecgooden** [comment]
This was caused by a compilation issue for the version that was on curseforge. I've uploaded fixed version here: https://github.com/gecgooden/chunkgen/releases/download/1.3.0/chunkgen-1.8.9-1.3.0.jar

The fix is pending on curseforge and will be available there soon.

**Comment by 7934345** [comment]
Ok, gonna have a test :)
